### ISSUE TITLE
Broken Domkit CSS example

### ISSUE THREAD

**Issue by tobil4sk** [HeapsIO/heaps-doc#84]
The Domkit section of the docs gives this CSS example:
```hx
class SampleView extends h2d.Flow implements h2d.domkit.Object {
    static var SRC = 
        // had to add the class="box" myself as it's missing from the example 
        <sample-view class="box" layout="vertical">
            <text text={"Hello World!"}/>
            <bitmap src={tile} public id="mybmp"/>
        </sample-view>

    public function new(tile:h2d.Tile,?parent) {
        super(parent);
        initComponent();
    }
}
```

```css
.box {
    padding : 20;
    background : #400;
}
```
Even if the `class="box"` is added to the sample-view so that this css is actually activated, this css then fails the compile time check because "padding" is not recognised:
```
res/style.css:3: characters 2-15 : Unknown property padding
```
Instead, the css could be modified to set properties for the SampleView itself:
```css
sample-view {
    padding : 20;
    background : #400;
}
```

However, the problem then is that it cannot find the component:
```
res/style.css:2: character 5 : Could not load component 'sample-view'
```
